source 'https://rubygems.org'
gem 'rails', '4.0.0'
gem 'sqlite3'
gem 'mysql2'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'therubyracer', platforms: :ruby
gem 'country_select'
gem 'redcarpet'
gem 'shoppe', :git => 'git://github.com/tryshoppe/core.git'
